### PR TITLE
[WIP] Add cloud-config files for CoreOS demo

### PR DESCRIPTION
**Pull request by caseydavenport**
Depends on Kubernetes v1.1 release - don't merge until released.

Config used by: https://github.com/kubernetes/kubernetes/pull/16380

### CODE REVIEW

**Comment by caseydavenport** [comment]
@Symmetric - if you have a spare minute, could you take a look to make sure this all looks sensible before I merge?

It works in accordance with the guide, but I'd like a second pair of eyes.

**Comment by Symmetric** [comment]
Looks fine. I'm sure we discussed this before, but I can't recall why we're not basing this off something like https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md - I suspect we'd need https://github.com/projectcalico/calico-kubernetes/issues/93 in this case, since it's harder (though not impossible?) to manually edit the unit files under CoreOS.

**Comment by Symmetric** [comment]
Also this punts on token auth -- which is something we'll want to include in all the docs I believe. (I'm just realizing this is going to be awkward under Vagrant, too)

**Comment by caseydavenport** [comment]
@Symmetric - currently not basing off of that guide since it is quite a bit older.  This uses containerized Kubernetes processes rather than systemd, 

This also sets up a cluster that looks very similar to the one that our Ubuntu guide sets up.

**Pull request merged**
